import { PrismaClient, UserRole, UserStatus } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

const users = [
  {
    no: '1',
    fullName: 'النظام / معلومات الشركة',
    firstName: 'abak engineering',
    lastName: 'consulting',
    email: 'info@abak.com.sa',
    technicalRole: 'System',
    jobTitle: 'نظام / حساب عام',
    department: 'الإدارة التنفيذية',
    productPersona: 'System / Company account',
    appRole: 'VIEWER',
    testFocus: 'System identity; avoid using as human actor',
    gap: 'OK',
  },
  {
    no: '2',
    fullName: 'عبد الغني الموفق',
    firstName: 'Abdulghani',
    lastName: 'Almuwafiq',
    email: 'abdulghani.almuwafiq@abak.com.sa',
    technicalRole: 'User',
    jobTitle: 'مستخدم',
    department: 'القسم المعماري',
    productPersona: 'Department Engineer / Pricer',
    appRole: 'TECHNICAL_MANAGER',
    testFocus: 'RFQ pricing, project tasks, licence dependencies',
    gap: 'Coarse role: app lacks separate DEPARTMENT_ENGINEER/MANAGER',
  },
  {
    no: '3',
    fullName: 'عبدالله محسن',
    firstName: 'Abdullah Mohsen',
    lastName: 'Abdullah',
    email: 'abdullah.mohsen@abak.com.sa',
    technicalRole: 'Super Admin',
    jobTitle: 'مدير قسم ال IT وتطوير الاعمال',
    department: 'الإدارة التنفيذية',
    productPersona: 'CEO / Super Admin',
    appRole: 'SUPER_ADMIN',
    testFocus: 'Admin, all modules, approvals, settings',
    gap: 'OK',
  },
  {
    no: '4',
    fullName: 'أحمد البيطار',
    firstName: 'Ahmad',
    lastName: 'Albitter',
    email: 'a.albittar@abak.com.sa',
    technicalRole: 'User',
    jobTitle: 'مستخدم',
    department: 'القسم المعماري',
    productPersona: 'Department Engineer / Pricer',
    appRole: 'TECHNICAL_MANAGER',
    testFocus: 'RFQ pricing, project tasks, licence dependencies',
    gap: 'Coarse role: app lacks separate DEPARTMENT_ENGINEER/MANAGER',
  },
  {
    no: '6',
    fullName: 'أحمد العبيري — محاسبة',
    firstName: 'Ahmed',
    lastName: 'Elibairy',
    email: 'accounting@abak.com.sa',
    technicalRole: 'Accountant',
    jobTitle: 'مسؤول قسم',
    department: 'الإدارة المالية',
    productPersona: 'Finance Officer',
    appRole: 'FINANCE_MANAGER',
    testFocus: 'Payments, invoices, finance validation',
    gap: 'OK',
  },
  {
    no: '7',
    fullName: 'أكرم عبدالله',
    firstName: 'Akram',
    lastName: 'Abdullah',
    email: 'akram@abak.com.sa',
    technicalRole: 'Administrator',
    jobTitle: 'مدير قسم',
    department: 'إدارة الخدمات البيئية',
    productPersona: 'Department Manager',
    appRole: 'ADMIN',
    testFocus: 'Department triage, reports, admin workflows',
    gap: 'OK',
  },
  {
    no: '8',
    fullName: 'علاء احمد',
    firstName: 'Alaa',
    lastName: 'Ahmed',
    email: 'alaa.ahmed@abak.com.sa',
    technicalRole: 'User',
    jobTitle: 'مستخدم',
    department: 'قسم المساحة',
    productPersona: 'Department Engineer / Pricer',
    appRole: 'TECHNICAL_MANAGER',
    testFocus: 'RFQ pricing, project tasks, licence dependencies',
    gap: 'Coarse role: app lacks separate DEPARTMENT_ENGINEER/MANAGER',
  },
  {
    no: '9',
    fullName: 'أمين النهاري',
    firstName: 'Ameen',
    lastName: 'Alnhari',
    email: 'ameen@abak.com.sa',
    technicalRole: 'User',
    jobTitle: 'مسؤول قسم',
    department: 'قسم الإشراف والهندسة المدنية',
    productPersona: 'Department Engineer / Pricer',
    appRole: 'TECHNICAL_MANAGER',
    testFocus: 'RFQ pricing, project tasks, licence dependencies',
    gap: 'Coarse role: app lacks separate DEPARTMENT_ENGINEER/MANAGER',
  },
  {
    no: '11',
    fullName: 'ضحى العوام',
    firstName: 'Duha',
    lastName: 'Al-awam',
    email: 'hr@abak.com.sa',
    technicalRole: 'HR Manager',
    jobTitle: 'مدير قسم',
    department: 'إدارة الموارد البشرية',
    productPersona: 'HR/Admin Viewer',
    appRole: 'VIEWER',
    testFocus: 'Non-MVP/support access check',
    gap: 'No HR role in current UserRole enum',
  },
  {
    no: '12',
    fullName: 'غادة العتيبي',
    firstName: 'Ghadah',
    lastName: 'Alotaibi',
    email: 'ghadah@abak.com.sa',
    technicalRole: 'User',
    jobTitle: 'مستخدم',
    department: 'قسم التسويق والمبيعات',
    productPersona: 'Sales Person',
    appRole: 'SALES_REPRESENTATIVE',
    testFocus: 'Lead/RFQ request/client communication',
    gap: 'OK',
  },
  {
    no: '13',
    fullName: 'هيثم محمدي',
    firstName: 'Haitham',
    lastName: 'Mohamady',
    email: 'haitham@abak.com.sa',
    technicalRole: 'Administrator',
    jobTitle: 'مدير قسم',
    department: 'قسم التسويق والمبيعات',
    productPersona: 'Department Manager',
    appRole: 'ADMIN',
    testFocus: 'Department triage, reports, admin workflows',
    gap: 'OK',
  },
  {
    no: '14',
    fullName: 'هاشم علي',
    firstName: 'Hashim',
    lastName: 'Ali',
    email: 'hashim.ali@abak.com.sa',
    technicalRole: 'User',
    jobTitle: 'مستخدم',
    department: 'القسم المعماري',
    productPersona: 'Department Engineer / Pricer',
    appRole: 'TECHNICAL_MANAGER',
    testFocus: 'RFQ pricing, project tasks, licence dependencies',
    gap: 'Coarse role: app lacks separate DEPARTMENT_ENGINEER/MANAGER',
  },
  {
    no: '15',
    fullName: 'حسن صلاح',
    firstName: 'Hassan',
    lastName: 'Salah',
    email: 'hassan@abak.com.sa',
    technicalRole: 'Administrator',
    jobTitle: 'مدير قسم المعماري ومدير مكتب إدارة المشاريع',
    department: 'إدارة جميع الاقسام الفنية',
    productPersona: 'Department Manager',
    appRole: 'ADMIN',
    testFocus: 'Department triage, reports, admin workflows',
    gap: 'OK',
  },
  {
    no: '16',
    fullName: 'خالد الخبيري',
    firstName: 'Khaled',
    lastName: 'Elkhabery',
    email: 'khaled@abak.com.sa',
    technicalRole: 'User',
    jobTitle: 'مستخدم',
    department: 'القسم المعماري',
    productPersona: 'Department Engineer / Pricer',
    appRole: 'TECHNICAL_MANAGER',
    testFocus: 'RFQ pricing, project tasks, licence dependencies',
    gap: 'Coarse role: app lacks separate DEPARTMENT_ENGINEER/MANAGER',
  },
  {
    no: '18',
    fullName: 'مسفر القحطاني',
    firstName: 'Mesfer',
    lastName: 'Alqahtani',
    email: 'mesfer@abak.com.sa',
    technicalRole: 'Administrator',
    jobTitle: 'رئيس مجلس الإدارة',
    department: 'الإدارة التنفيذية',
    productPersona: 'Sales/Business Manager or Main Manager',
    appRole: 'ADMIN',
    testFocus: 'Department triage, reports, admin workflows',
    gap: 'OK',
  },
  {
    no: '20',
    fullName: 'محمد العطيات — علاقات عملاء',
    firstName: 'Mohammed',
    lastName: 'Alatiyyat',
    email: 'client.relations2@abak.com.sa',
    technicalRole: 'User',
    jobTitle: 'مستخدم',
    department: 'قسم التسويق والمبيعات',
    productPersona: 'Sales Person',
    appRole: 'SALES_REPRESENTATIVE',
    testFocus: 'Lead/RFQ request/client communication',
    gap: 'OK',
  },
  {
    no: '21',
    fullName: 'محمد العياف',
    firstName: 'Mohammed',
    lastName: 'Alayaf',
    email: 'm.alayaf@abak.com.sa',
    technicalRole: 'Administrator',
    jobTitle: 'الرئيس التنفيذي',
    department: 'الإدارة التنفيذية',
    productPersona: 'Sales/Business Manager or Main Manager',
    appRole: 'ADMIN',
    testFocus: 'Department triage, reports, admin workflows',
    gap: 'OK',
  },
  {
    no: '22',
    fullName: 'محمد ضيف الله',
    firstName: 'Mohammed',
    lastName: 'Deifallah',
    email: 'mohammed.deifallah@abak.com.sa',
    technicalRole: 'User',
    jobTitle: 'مستخدم',
    department: 'قسم المساحة',
    productPersona: 'Department Engineer / Pricer',
    appRole: 'TECHNICAL_MANAGER',
    testFocus: 'RFQ pricing, project tasks, licence dependencies',
    gap: 'Coarse role: app lacks separate DEPARTMENT_ENGINEER/MANAGER',
  },
  {
    no: '23',
    fullName: 'مصطفى حلمي',
    firstName: 'Mostafa',
    lastName: 'Helmy',
    email: 'mostafa@abak.com.sa',
    technicalRole: 'User',
    jobTitle: 'مستخدم',
    department: 'قسم التسويق والمبيعات',
    productPersona: 'Sales Person',
    appRole: 'SALES_REPRESENTATIVE',
    testFocus: 'Lead/RFQ request/client communication',
    gap: 'OK',
  },
  {
    no: '25',
    fullName: 'عمر ربابعة',
    firstName: 'Omar',
    lastName: 'Rababah',
    email: 'omar@abak.com.sa',
    technicalRole: 'User',
    jobTitle: 'مدير قسم',
    department: 'قسم السلامة والأمن الصناعي',
    productPersona: 'Department Engineer / Pricer',
    appRole: 'TECHNICAL_MANAGER',
    testFocus: 'RFQ pricing, project tasks, licence dependencies',
    gap: 'Coarse role: app lacks separate DEPARTMENT_ENGINEER/MANAGER',
  },
  {
    no: '26',
    fullName: 'أسامة الصامت',
    firstName: 'Osamah',
    lastName: 'Alsamet',
    email: 'osamah.alsamet@abak.com.sa',
    technicalRole: 'User',
    jobTitle: 'مستخدم',
    department: 'القسم المعماري',
    productPersona: 'Department Engineer / Pricer',
    appRole: 'TECHNICAL_MANAGER',
    testFocus: 'RFQ pricing, project tasks, licence dependencies',
    gap: 'Coarse role: app lacks separate DEPARTMENT_ENGINEER/MANAGER',
  },
  {
    no: '28',
    fullName: 'رحمة طارق — علاقات عملاء',
    firstName: 'Rahma',
    lastName: 'Tareq',
    email: 'client.relations1@abak.com.sa',
    technicalRole: 'Client Relations',
    jobTitle: 'مستخدم',
    department: 'قسم التسويق والمبيعات',
    productPersona: 'Sales Person / Client Relations',
    appRole: 'SALES_REPRESENTATIVE',
    testFocus: 'Lead capture, follow-ups, quote dispatch',
    gap: 'OK',
  },
  {
    no: '29',
    fullName: 'صالح الشهري',
    firstName: 'Saleh',
    lastName: 'Alshehri',
    email: 'salshehri@abak.com.sa',
    technicalRole: 'User',
    jobTitle: 'المدير التنفيذي — تطوير الأعمال',
    department: 'الإدارة التنفيذية',
    productPersona: 'Executive Viewer',
    appRole: 'VIEWER',
    testFocus: 'Dashboard/report visibility',
    gap: 'OK',
  },
  {
    no: '30',
    fullName: 'سلوى سعد',
    firstName: 'Salwa',
    lastName: 'Saad',
    email: 'salwa@abak.com.sa',
    technicalRole: 'User',
    jobTitle: 'مستخدم',
    department: 'قسم التسويق والمبيعات',
    productPersona: 'Sales Person',
    appRole: 'SALES_REPRESENTATIVE',
    testFocus: 'Lead/RFQ request/client communication',
    gap: 'OK',
  },
  {
    no: '32',
    fullName: 'وليد بن عابد',
    firstName: 'Waleed',
    lastName: 'bin Abid',
    email: 'w.abid@abak.com.sa',
    technicalRole: 'User',
    jobTitle: 'مستخدم',
    department: 'قسم السلامة والأمن الصناعي',
    productPersona: 'Department Engineer / Pricer',
    appRole: 'TECHNICAL_MANAGER',
    testFocus: 'RFQ pricing, project tasks, licence dependencies',
    gap: 'Coarse role: app lacks separate DEPARTMENT_ENGINEER/MANAGER',
  },
] as const;

async function main() {
  const password = process.env.ABAK_TEST_USER_PASSWORD;
  if (!password) {
    throw new Error(
      'Set ABAK_TEST_USER_PASSWORD before running. Do not commit/share real passwords.',
    );
  }
  const hashedPassword = await bcrypt.hash(password, 10);

  for (const user of users) {
    await prisma.user.upsert({
      where: { email: user.email },
      create: {
        email: user.email,
        password: hashedPassword,
        firstName: user.firstName,
        lastName: user.lastName,
        role: user.appRole as UserRole,
        status: UserStatus.ACTIVE,
        emailVerified: true,
      },
      update: {
        firstName: user.firstName,
        lastName: user.lastName,
        role: user.appRole as UserRole,
        status: UserStatus.ACTIVE,
        emailVerified: true,
      },
    });
  }

  console.log(`Upserted ${users.length} Abak test users.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
